.TH POLYPHONE "1" "August 12, 2014" "polyphone 1.4" "Polyphone Manual Page"

.SH NAME
\fBpolyphone\fP \- soundfont editor

.SH SYNOPSIS
.B polyphone
[\fIFILE\fR...]

.SH DESCRIPTION
.B polyphone
provides a simple and efficient interface for creating and editing .sf2 files. This software comprises tools to facilitate and automate the editing of different parameters, making it possible to handle a large amount of data.
sfz (import / export) and sfArk (import only) formats are supported.
.br
.PP
More information can be found at http://www.polyphone.fr.

.SH OPTIONS
.TP
\fBFILE\fR
Specifies the file to open when
.B polyphone
starts. Multiple files can be loaded if they are separated by spaces.
sf2 (version 2.01 or 2.04), sfz and sfArk (version 1 or 2) formats are supported.

.SH AUTHOR
Davy Triponney (davy.triponney@gmail.com)
